name: InvulnerableItems
main: net.evmodder.InvulnerableItems.InvulnerableItems
author: EvModder
description: Make specific items resist specific damage sources.
website: https://github.com/EvModder/InvulnerableItems
version: 1.1
api-version: 1.13
softdepend: [DropHeads]